# Generated by Django 3.1.2 on 2020-10-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201028_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics', verbose_name='profile image'),
        ),
    ]
