# Generated by Django 3.1.2 on 2020-11-01 19:43

import cloudinary.models
from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201028_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(default=users.models.image_default, max_length=255, validators=[users.models.validate_image], verbose_name='profile image'),
        ),
    ]
