# Generated by Django 3.1.2 on 2020-10-28 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='course_pics', verbose_name='image')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(choices=[], max_length=20, verbose_name='category')),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('zh', 'Chinese'), ('es', 'Spanish'), ('fr', 'French')], max_length=3, verbose_name='language')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='start date')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', related_query_name='created_course', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(db_table='participation', related_name='attended_courses', related_query_name='attended_course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
