# Generated by Django 3.1.2 on 2020-10-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201028_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('photography', 'Photography'), ('design', 'Design'), ('arts', 'Arts'), ('business', 'Business'), ('language_learning', 'Language learning'), ('programming', 'Programming'), ('health', 'Health'), ('social_science', 'Social science'), ('engineering', 'Engineering'), ('math', 'Mathematics')], max_length=50, verbose_name='category'),
        ),
    ]
