# Generated by Django 3.1.2 on 2020-10-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20201028_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course_pics/default.png', upload_to='course_pics', verbose_name='image'),
        ),
    ]
