# Generated by Django 3.1.2 on 2020-10-30 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20201028_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('photography', 'Photography'), ('design', 'Design'), ('arts', 'Arts'), ('business', 'Business'), ('language', 'Language'), ('programming', 'Programming'), ('health', 'Health'), ('social_science', 'Social science'), ('engineering', 'Engineering'), ('math', 'Mathematics')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='start date'),
        ),
    ]
