# Generated by Django 3.1.2 on 2020-11-06 18:31

import cloudinary.models
import courses.services
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20201030_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=cloudinary.models.CloudinaryField(default=courses.services.get_default_course_image, max_length=255, validators=[courses.services.validate_course_image], verbose_name='image'),
        ),
    ]
