# Generated by Django 3.1.2 on 2020-11-01 19:36

import cloudinary.models
import courses.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20201030_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=cloudinary.models.CloudinaryField(default=courses.models.image_default, max_length=255, validators=[courses.models.validate_image], verbose_name='image'),
        ),
    ]
