# Generated by Django 3.1.2 on 2020-12-09 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0011_auto_20201209_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', related_query_name='participation', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', related_query_name='participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
