# Generated by Django 3.1.2 on 2020-12-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20201209_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
        migrations.AddField(
            model_name='solution',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
